version: "2"

services:

  kafka:
    image: hyperledger/fabric-kafka:latest
    environment:
      - TZ=Asia/Seoul
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 Byte
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 Byte
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LOG4J_ROOT_LOGLEVEL=WARN # INFO로 변경해해서 REPLICATION 되는것 확인
      - KAFKA_TOOLS_LOG4J_LOGLEVEL=ERROR
      # - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=${KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES}
