version: "3"

networks:
    internet:
    client_net:
    server_net:

services:

    server_gw:
        image: nginx
        volumes:
            - "./greeter_server/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./greeter_server/nginx/conf.d:/etc/nginx/conf.d"
        networks:
            server_net:
                aliases:
                    - "greeter.client"
            internet:
                aliases:
                    - "greeter.server.gw"

    client_gw:
        image: nginx
        volumes:
            - "./greeter_client/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./greeter_client/nginx/conf.d:/etc/nginx/conf.d"
        networks:
            client_net:
                aliases:
                    - "greeter.server"
            internet:
                aliases:
                    - "greeter.client.gw"
 
    greeter_server:
        build:
            context: .
            dockerfile: ./greeter_server/Dockerfile
        networks:
            server_net:
                aliases:
                    - "greeter.server"

    greeter_client:
        build:
            context: .
            dockerfile: ./greeter_client/Dockerfile
        ports:
            - 80:80
        networks:
            client_net:
                aliases:
                    - "greeter.client"
