version: "3"

networks:
  basic:

services:
  rsyslog:
    image: rsyslog/rsyslog_base_centos7
    container_name: rsyslog
    ports:
      - 10514:10514/udp
    volumes:
      - "./rsyslog.conf:/etc/rsyslog.conf"
      - "./log/nginx:/var/log/syslog"
    command: /sbin/rsyslogd -n

  rsyslog_nginx:
    image: nginx
    container_name: rsyslog_nginx
    ports:
      - 8080:80
    logging:
      # @see https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        # @ see https://docs.docker.com/docker-for-mac/networking/
        # >> I WANT TO CONNECT TO A CONTAINER FROM THE MAC
        syslog-address: "udp://host.docker.internal:10514"
        syslog-facility: "local0"
        tag: "{{.Name}}"

    depends_on:
      - rsyslog
