version: "3"

networks:
    internet:
    org1_net:
    org2_net:
    org3_net:

services:
    org1_gw:
        image: nginx
        ports:
            - 17050:7050
            - 17051:7051
        volumes:
            - "./org1-nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./org1-nginx/conf.d:/etc/nginx/conf.d"
        networks:
            org1_net:
                aliases:
                    - "peer1.org2"
                    - "peer2.org2"
                    - "peer1.org3"
                    - "peer2.org3"
            internet:
                aliases:
                    - "org1.gw"

    org2_gw:
        image: nginx
        ports:
            - 27050:7050
            - 27051:7051
        volumes:
            - "./org2-nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./org2-nginx/conf.d:/etc/nginx/conf.d"
        networks:
            org2_net:
                aliases:
                    - "orderer1.ordererorg"
                    - "orderer2.ordererorg"
                    - "peer1.org1"
                    - "peer2.org1"
                    - "peer1.org3"
                    - "peer2.org3"
            internet:
                aliases:
                    - "org2.gw"

    org3_gw:
        image: nginx
        ports:
            - 37050:7050
            - 37051:7051
        volumes:
            - "./org3-nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./org3-nginx/conf.d:/etc/nginx/conf.d"
        networks:
            org3_net:
                aliases:
                    - "orderer1.ordererorg"
                    - "orderer2.ordererorg"
                    - "peer1.org1"
                    - "peer2.org1"
                    - "peer1.org2"
                    - "peer2.org2"
            internet:
                aliases:
                    - "org3.gw"


    orderer1_ordererorg:
        build:
            context: .
            dockerfile: ./greeter_server/Dockerfile
            args:
                host: "orderer1.ordererorg"
                port: 7050
        networks:
            - org1_net

    peer1_org1:
        build:
            context: .
            dockerfile: ./greeter_server/Dockerfile
            args:
                host: "peer1.org1"
                port: 7051
        networks:
            - org1_net

    peer1_org2:
        build:
            context: .
            dockerfile: ./greeter_server/Dockerfile
            args:
                host: "peer1.org2"
                port: 7051
        networks:
            - org2_net

    peer1_org3:
        build:
            context: .
            dockerfile: ./greeter_server/Dockerfile
            args:
                host: "peer1.org3"
                port: 7051
        networks:
            - org3_net

    orderer1_tester:
        build:
            context: .
            dockerfile: ./greeter_client/Dockerfile
            args:
                host: "orderer1.ordererorg"
        ports:
            - 17080:80
        networks:
            - org1_net
    orderer2_tester:
        build:
            context: .
            dockerfile: ./greeter_client/Dockerfile
            args:
                host: "orderer2.ordererorg"
        ports:
            - 17081:80
        networks:
            - org1_net

    org1_peer1_tester:
        build:
            context: .
            dockerfile: ./greeter_client/Dockerfile
            args:
                host: "peer1.org1"
        ports:
            - 17180:80
        networks:
            - org1_net
    org1_peer2_tester:
        build:
            context: .
            dockerfile: ./greeter_client/Dockerfile
            args:
                host: "peer2.org1"
        ports:
            - 17181:80
        networks:
            - org1_net

    org2_peer1_tester:
        build:
            context: .
            dockerfile: ./greeter_client/Dockerfile
            args:
                host: "peer1.org2"
        ports:
            - 17280:80
        networks:
            - org2_net
    org2_peer2_tester:
        build:
            context: .
            dockerfile: ./greeter_client/Dockerfile
            args:
                host: "peer2.org2"
        ports:
            - 17281:80
        networks:
            - org2_net

    org3_peer1_tester:
        build:
            context: .
            dockerfile: ./greeter_client/Dockerfile
            args:
                host: "peer1.org3"
        ports:
            - 17380:80
        networks:
            - org3_net
    org3_peer2_tester:
        build:
            context: .
            dockerfile: ./greeter_client/Dockerfile
            args:
                host: "peer2.org3"
        ports:
            - 17381:80
        networks:
            - org3_net
